---
kind: pipeline
type: docker
name: minio

steps:
  - name: wait-for-minio
    image: ruanbekker/curl
    commands:
      - while ! curl -sf http://minio:9000/minio/health/live; do sleep 1; done

  - name: create-bucket
    image: minio/mc
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: SHDUEHSNKFOEJDNCYEXAMPLEKEY
    commands:
      - mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
      - mc mb minio/mybucket

  - name: write-to-bucket
    image: minio/mc
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: SHDUEHSNKFOEJDNCYEXAMPLEKEY
    commands:
      - mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
      - echo $RANDOM | sha256sum > file.txt
      - mc cp file.txt minio/mybucket/content/file.txt

  - name: read-from-bucket
    image: minio/mc
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: SHDUEHSNKFOEJDNCYEXAMPLEKEY
    commands:
      - mc alias set minio http://minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
      - mc cat minio/mybucket/content/file.txt

services:
  - name: minio
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: AKIAIOSFODNN7EXAMPLE
      MINIO_ROOT_PASSWORD: SHDUEHSNKFOEJDNCYEXAMPLEKEY
    command: [ "server", "/data"]
